apiVersion: v1
kind: Service
metadata:
  name: elevechallengeexchange-service
spec:
  type: LoadBalancer
  selector:
    app: elevechallengeexchange
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
